language: android
jdk: oraclejdk8
sudo: false

before_install:
    # Making sure gradlew has executable permissions
    - cd TheMovieGuide
    - chmod a+x gradlew
    - yes | sdkmanager "platforms;android-28"

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by our project
    - build-tools-28.0.2

    # The SDK version used to compile our project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

    script: ./gradlew assembleDebug